security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
       in_database:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            provider: in_database
            form_login:
                login_path: login
                check_path: login
            logout: 
                path: logout
                target: login

    access_control:
        - { path: ^/login, roles: IS_ANONYMOUS }
        - { path: ^/, roles: [ROLE_USER, ROLE_ADMIN] }
