language: php

php:
  - '7.4'

cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/symfony-bridge/.phpunit
        
services:
  - mysql
 
before_install:
  - cp .env.travis .env

install:
  - composer install

before_script:
  - php bin/console doctrine:database:create
  - php bin/console doctrine:schema:create
  - php bin/console doctrine:fixtures:load -n

script:
  - vendor/bin/phpunit